### ISSUE TITLE
CUDA runtime error 30

### ISSUE THREAD

**Issue by matthiasplappert** [torch/cutorch#197]
Hey everyone,

I'm using cutorch to train a deep convolutional NN. Concretely, I use the code provided by Google DeepMind for training a NN to play Atari 2600 games. A mirror with a minor fix for the CUDA code can be found here: https://github.com/soumith/deepmind-atari

Everything works great for a quite some time after starting training. However, after about 300,000 steps (+- a couple of thousand steps) things start go wrong. Here's the stderr message that I receive just before the program crashes:
```
luajit: cuda runtime error (30) : unknown error at /tmp/luarocks_cutorch-scm-1-9927/cutorch/lib/THC/THCStorage.c:113
```
I've tried to google the runtime error, but it seems like this is not something that surfaces often. Does anybody here have an idea what could cause this?

I've also included some information on the system and software that I use:
- Ubuntu 14.04
- GeForce GTX 570
- nvidia driver: 331.113
- LuaJIT 2.0.3
- Latest torch + libraries (fresh install today)
If you need additional information, please let me know.

Any help here is greatly appreciated!

**Comment by soumith** [comment]
hi, an unknown error from the nvidia driver usually means that it's something weird at the driver level, or the GPU is bad.

Is the GPU overheating?
Can you upgrade to latest NVIDIA drivers?
Can you run gpu-burn to stress test your GPU and make sure the memory does not have bad regions etc.

http://wili.cc/blog/gpu-burn.html

**Comment by matthiasplappert** [comment]
Thanks for the extremely fast response. I'm currently running `cuda_memtest` and will run `gpu-burn` afterwards. Unfortunately I cannot update the driver myself since I do not have rights to do so on the computer that I use.

I guess it is likely that this is a problem with my specific card and not cutorch. I'll therefore go ahead and close this issue.

Thanks again for the pointers!

**Comment by matthiasplappert** [comment]
FYI and for future reference: this was indeed caused by a malfunctioning/overheating GPU. I'm now running the same code on an EC2 instance and it works flawlessly.

**Comment by hughperkins** [comment]
EC2 rocks :-)
