### ISSUE TITLE
Illegal memory access THCTensorCopy.c

### ISSUE THREAD

**Issue by aleSuglia** [torch/cutorch#361]
Hello,
I'm using Torch to implement a custom model which uses rnn and the CUDA libraries.
Actually I'm having some problems and when the training starts I obtain the following error message:
```
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7652/cutorch/lib/THC/generic/THCTensorCopy.c line=18 error=77 : an illegal memory access was encountered
/home/recsyserver/torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-7652/cutorch/lib/THC/generic/THCStorage.c:147
```
I tried to reinstall Torch from scratch and to install all the needed libraries (in the order: nn, cutorch, cunn, rnn) without success on Ubuntu 14.04 using the latest version of the CUDA libraries.
How can I solve my problem?

I tried to use the flag  `CUDA_LAUNCH_BLOCKING=1` suggested by @soumith in another issue message and this is the detailed error message that I got:
```
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-7652/cutorch/lib/THC/THCTensorMathPairwise.cu line=72 error=77 : an illegal memory access was encountered
/home/recsyserver/torch/install/bin/luajit: cuda runtime error (77) : an illegal memory access was encountered at /tmp/luarocks_cutorch-scm-1-7652/cutorch/lib/THC/generic/THCStorage.c:147 
```

Thank you in advance for your help.
Alessandro

**Comment by soumith** [comment]
i need a code snippet to reproduce this. a minimal ~50 line sample of code.

**Comment by aleSuglia** [comment]
Thank you for your answer.

Unfortunately, I cannot give you a complete test case because you need the dataset and some supplementary information associated to it. I can give you the model code because I'm pretty sure that you will be able to understand how I pass the data to it:

```
function build_model(items_data, ratings_data)
   local embeddings_size = 10
   local hidden_dense_layer_size = 2 * embeddings_size

   local items_model = nn.Sequential()
        :add(nn.LookupTableMaskZero(items_data["num_tokens"] + 1, embeddings_size))
        :add(nn.SplitTable(2))
        :add(nn.Sequencer(nn.LSTM(embeddings_size, embeddings_size)))
        :add(nn.CAddTable())
        :add(nn.Normalize(2))

    local users_model = nn.Sequential()
        :add(nn.LookupTable(ratings_data["num_users"], embeddings_size))

    local full_model = nn.Sequential() -- {item, user}

    full_model:add(nn.ParallelTable()
                    :add(items_model)
                    :add(users_model))
        :add(nn.JoinTable(2))
        :add(nn.Linear(hidden_dense_layer_size, 1))
        :add(nn.Sigmoid())

   return full_model
end
```

If you want any other information I'm pleased to support you.

**Comment by fmassa** [comment]
@aleSuglia Do you face the same problem if you feed to the network random data ? Say a random input and random (but meaningful) targets ? If you manage to reproduce the problem with random data, then it's going to be easier to track the problem.

**Comment by soumith** [comment]
it's likely that you are giving an input to the lookuptable that's out of bounds (i.e. you have 10K word embeddings in your LookupTable and you maybe asked for 10002th element)

**Comment by aleSuglia** [comment]
I'll try to find the reason for the error but in the meantime please don't close this issue. I'll update this issue as soon as I can with additional information.

Thank you again!

**Comment by aleSuglia** [comment]
I have done a huge refactoring and I have found the problem. For a specific dataset, some indices are not properly given in input to the LookupTable. I've fixed it and the problem disappeared.
Thank you both very much!

**Comment by tastyminerals** [comment]
@aleSuglia I am experiencing the same issue with a non-English dataset. Can you please share what did you modify to resolve the issue?

**Comment by aleSuglia** [comment]
Sorry, but my problem seems not be related to the cutorch library. Have a look at the indexes that you use in order to generate your distributed representations because maybe you are using invalid indexes.

**Comment by Cadene** [comment]
I solved a similar problem by saving my network between each epoch that way :
`torch.save('net.t7', net:clone():clearState():float())`

instead of
`torch.save('net.t7, net:clearState())`
