### ISSUE TITLE
CudaTensor.index causing buggy state in CUDA 3.5?

### ISSUE THREAD

**Issue by insperatum** [torch/cutorch#686]
I'm using an older GPU (Tesla K20, cuda compute capability 3.5) and getting a very strange error, demonstrated below. Note that the command `t[1] = t[1]` will execute initially, but after line 4 the system enters an odd state where this command causes an 'invalid device function' error. The command runs fine again after the first failed attempt.

```
th> require 'cutorch'
                                                                      [4.1952s]	
th> t = torch.CudaTensor(1,2)
                                                                      [0.0001s]	
th> t[1] = t[1]
                                                                      [0.0002s]	
th> torch.CudaTensor(5):index(1, torch.LongTensor{2,3})
 0
 0
[torch.CudaTensor of size 2]

                                                                      [0.0008s]	
th> t[1] = t[1]
THCudaCheck FAIL file=/tmp/luarocks_cutorch-scm-1-926/cutorch/lib/THC/THCTensorCopy.cu line=205 error=8 : invalid device function
cuda runtime error (8) : invalid device function at /tmp/luarocks_cutorch-scm-1-926/cutorch/lib/THC/THCTensorCopy.cu:205
stack traceback:
	[C]: at 0x2b82041886e0
	[C]: in function '__newindex'
	[string "t[1] = t[1]"]:1: in main chunk
	[C]: in function 'xpcall'
	/home/lbh/torch/install/share/lua/5.1/trepl/init.lua:670: in function 'repl'
	.../lbh/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:199: in main chunk
	[C]: at 0x004064f0	
                                                                      [0.0004s]	
th> t[1] = t[1]
                                                                      [0.0001s]	
```

**Comment by soumith** [comment]
did you compile cutorch on your own machine?
"invalid device function" points to where you might have built cutorch on a machine with a different GPU capability and copied over

**Comment by insperatum** [comment]
Ah, had compiled on a cluster machine with different specs. Just recompiled and that fixed it. Thank you for being so responsive!

**Comment by insperatum** [comment]
@soumith The field of deep learning should hold an annual celebration in honour of your huge contribution.
