### ISSUE TITLE
Caching allocator (enabled by default now?) causes cuda OOM

### ISSUE THREAD

**Issue by vadimkantorov** [torch/cutorch#707]
I've installed a fresh Torch on a new machine recently. My code started to OOM.

I have a function that allocates a few thousand medium-sized local CudaTensors (4Gb worth of memory). nil'ing the table with these tensors and calling `collectgarbage` didn't help to free the memory.

I do not have `THC_CACHING_ALLOCATOR` set to 1, but I gave it a try by explicitly setting `export THC_CACHING_ALLOCATOR=0`. It solved the problem. It seems the caching allocator is enabled by default now.

Is there a way to flush the allocator's cache from Torch? (I guess it'd be a binding for https://github.com/torch/cutorch/blob/master/lib/THC/THCCachingAllocator.cpp#L172). For now I'll be disabling the allocator for my code.

The fact that the code OOMs suggests the allocator doesn't handle well near-OOM situation or that there are some allocations (inside cublas?) that bypass the caching allocator.

**Comment by colesbury** [comment]
Do you have a repro script? I know the cuDNN calls we use allocate device memory outside the caching allocator, but I didn't think cuBLAS did.

**Comment by vadimkantorov** [comment]
I will check if my code still blows with the caching allocator. I vaguely remember the crash was inside some matrix multiply code, but I'll let you know when I check it.

A manual forced release of unused blocks may still be useful for situations of using external libraries like cuDNN, and maybe some nasty allocation patterns.

**Comment by marcel1991** [comment]
How do you disable the caching allocator? Where do you set the flag to false? 

I have the same problem that after a cutorch update my memory usage is now higher and I can only use a smaller batch size compared to before.

**Comment by soumith** [comment]
you set it in your terminal before you run torch:

```
export THC_CACHING_ALLOCATOR=0
th foo.lua
```

**Comment by marcel1991** [comment]
Okay thank you! That solved the OOM problem.

**Comment by soumith** [comment]
do you have a small script that can reproduce your issue? that'll help us fix this once and for all.

**Comment by marcel1991** [comment]
No just a huge one :/ If you are talking to me.

**Comment by vadimkantorov** [comment]
For me back then it happened, when I allocated a big list of tensors, each of whose were of different size (like `#rois x 128`). And when this list went out of range and new list was allocated this same memory was not well reused.
