### ISSUE TITLE
THCTensorCopy.c line=18 error=4 : unspecified launch failure

### ISSUE THREAD

**Issue by hphong591992** [torch/cutorch#736]
I wrote a script that was able to run for like a month without any issue. Whenever I ran, it took a day.

Now, I start having this error when I want to copy data from a Tensor to CudaTensor. I think there's a segmentation fault here, but I don't know that's the fix or if this is a hardware issue.

It's not the GPU issue since I switched GPU and it causes the same error. The only hardware error that I can think of is because of the RAM, but I doubt that.

**Comment by soumith** [comment]
running your script with:

`CUDA_LAUNCH_BLOCKING=1 th script.lua`

might give more hints as to what the problem is.

**Comment by hphong591992** [comment]
Thank you Soumith, the error is segmentation fault. It appears at random locations in the code whenever I perform a copy similar to
```Lua
a = torch.CudaTensor(5)  
b = torch.DoubleTensor({1, 2, 3, 4, 5}) 
a:copy(b)
```

I don't know what's the fix at this point yet.

**Comment by soumith** [comment]
@gchanan can you reproduce the same issue locally?

**Comment by hphong591992** [comment]
Technically the code isn't this simple. It has the copy function to feed into the LSTM model (implementation from fb-rnnlib). I ran the code training on COCO, and the error randomly occurs.

**Comment by soumith** [comment]
ok in that case, the copy is unlikely the issue. It is likely that the error is reported when the copy happens (cuda errors are asynchronously reported).

**Comment by soumith** [comment]
i hoped that having the environment variable `CUDA_LAUNCH_BLOCKING=1 ` would give more hints, but looks like not.

**Comment by hphong591992** [comment]
Looking at the error, I checked this chunk of code
```C
    THCudaCheck(cudaMemcpy(THCTensor_(data)(state,selfc),
                           THTensor_(data)(src),
                           THTensor_(nElement)(src) * sizeof(real),
                           cudaMemcpyHostToDevice));
```

The error occurs at the kind (cudaMemcpyHostToDevice).
I suspect that the error is with the function cudaMemcpy. Maybe cudaMemcpyAsync is a solution?

**Comment by hphong591992** [comment]
@soumith I found out that the error is hardware issue. I reset BIOS to default mode, reinstall Ubuntu, install CUDA again, and it works.
